// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Follower struct {
	ID          int64        `json:"id"`
	FollowerID  int64        `json:"follower_id"`
	FollowingID int64        `json:"following_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Like struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	PostID    sql.NullInt64 `json:"post_id"`
	CommentID sql.NullInt64 `json:"comment_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Post struct {
	ID           int64         `json:"id"`
	UserID       int64         `json:"user_id"`
	Body         string        `json:"body"`
	Likes        int64         `json:"likes"`
	Comments     int64         `json:"comments"`
	ParentPostID sql.NullInt64 `json:"parent_post_id"`
	CreatedAt    time.Time     `json:"created_at"`
}

type Profile struct {
	UserID    int64          `json:"user_id"`
	Bio       sql.NullString `json:"bio"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	JoinAt    sql.NullTime   `json:"join_at"`
}

type User struct {
	ID             int64         `json:"id"`
	Username       string        `json:"username"`
	Password       string        `json:"password"`
	FollowingCount sql.NullInt32 `json:"following_count"`
	FollowerCount  sql.NullInt32 `json:"follower_count"`
	Email          string        `json:"email"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}
