// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Follower struct {
	ID          int64 `json:"id"`
	FollowerID  int64 `json:"follower_id"`
	FollowingID int64 `json:"following_id"`
}

type Post struct {
	ID        int64        `json:"id"`
	UserID    int32        `json:"user_id"`
	Title     string       `json:"title"`
	Body      string       `json:"body"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID             int64         `json:"id"`
	Username       string        `json:"username"`
	Password       string        `json:"password"`
	Email          string        `json:"email"`
	FollowerCount  sql.NullInt32 `json:"follower_count"`
	FollowingCount sql.NullInt32 `json:"following_count"`
}
