// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddLike(ctx context.Context, arg AddLikeParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecreaseFollowerCount(ctx context.Context, id int64) error
	DecreaseFollowingCount(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	EditPost(ctx context.Context, arg EditPostParams) (Post, error)
	FollowUser(ctx context.Context, arg FollowUserParams) (Follower, error)
	GetLike(ctx context.Context, arg GetLikeParams) (Like, error)
	GetPost(ctx context.Context, id int64) ([]GetPostRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	IncrementFollowerCount(ctx context.Context, id int64) error
	IncrementFollowingCount(ctx context.Context, id int64) error
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	LogIn(ctx context.Context, username string) (User, error)
	UnAddLike(ctx context.Context, arg UnAddLikeParams) error
	UnFollowUser(ctx context.Context, arg UnFollowUserParams) error
	UpdateLikesCount(ctx context.Context, postID sql.NullInt64) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
