// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePost(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	FollowUser(ctx context.Context, arg FollowUserParams) (Follower, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUser(ctx context.Context, id int64) (User, error)
	IncrementFollowerCount(ctx context.Context, id int64) error
	IncrementFollowingCount(ctx context.Context, id int64) error
	ListPosts(ctx context.Context) ([]Post, error)
	ListUsers(ctx context.Context) ([]User, error)
	LogIn(ctx context.Context, arg LogInParams) (User, error)
}

var _ Querier = (*Queries)(nil)
